# leaf.sh - Beautiful documentation and landing page generator
# Version: 2.2.0
# Generated by hammer.sh

set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
CYAN='\\033[0;36m'
MAGENTA='\\033[0;35m'
NC='\\033[0m' # No Color

# Default configuration
PROJECT_DIR="${1:-.}"
OUTPUT_DIR="${PROJECT_DIR}/docs"
MODE="docs" # docs or landing
LOGO_PATH=""
BASE_PATH="/"
GITHUB_URL="https://github.com/butter-sh"
PRIMARY_COLOR="#86efac"
SECONDARY_COLOR="#4ade80"
PROJECTS_FILE=""

# Dependency check
check_dependencies() {
	local missing_deps=()

	if ! command -v yq &>/dev/null; then
		missing_deps+=("yq")
	fi

	if ! command -v jq &>/dev/null; then
		missing_deps+=("jq")
	fi

	if [ ${#missing_deps[@]} -gt 0 ]; then
		log_error "Missing required dependencies: ${missing_deps[*]}"
		log_info "Install yq: https://github.com/mikefarah/yq#install"
		log_info "Install jq: https://stedolan.github.io/jq/download/"
		return 1
	fi

	return 0
}

# Helper functions
log_info() {
	echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
	echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
	echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
	echo -e "${RED}✗${NC} $1"
}

log_debug() {
	if [[ "${DEBUG:-0}" == "1" ]]; then
		echo -e "${MAGENTA}🔍${NC} $1"
	fi
}

# Show usage
show_usage() {
	cat <<EOF
${CYAN}╔═══════════════════════════════════════════╗${NC}
${CYAN}║                                           ║${NC}
${CYAN}║   🌿 leaf.sh - Documentation Generator   ║${NC}
${CYAN}║                                           ║${NC}
${CYAN}╚═══════════════════════════════════════════╝${NC}

${GREEN}DESCRIPTION:${NC}
    leaf.sh generates beautiful static HTML documentation from arty.sh projects
    and creates stylish landing pages for butter.sh with modern design.

${GREEN}USAGE:${NC}
    ${CYAN}# Generate documentation for arty.sh project${NC}
    leaf.sh [project-dir] [options]
    
    ${CYAN}# Generate butter.sh landing page${NC}
    leaf.sh --landing [options]

${GREEN}OPTIONS:${NC}
    ${YELLOW}--landing${NC}              Generate butter.sh landing page instead of docs
    ${YELLOW}--logo${NC} PATH            Path to logo/icon file
    ${YELLOW}--base-path${NC} PATH       Base path for HTML links (default: /)
    ${YELLOW}--github${NC} URL           GitHub organization URL (default: https://github.com/butter-sh)
    ${YELLOW}--projects${NC} JSON        JSON array of projects for landing page
    ${YELLOW}--projects-file${NC} FILE   JSON file containing projects array
    ${YELLOW}-o, --output${NC} DIR       Output directory (default: docs)
    ${YELLOW}-h, --help${NC}             Show this help message
    ${YELLOW}--version${NC}              Show version information
    ${YELLOW}--debug${NC}                Enable debug output

${GREEN}DOCUMENTATION MODE:${NC}
    Generates beautiful static HTML documentation from an arty.sh project
    including README, source files, examples, and project metadata.

    ${CYAN}Features:${NC}
    • Modern, responsive design with Tailwind CSS
    • Syntax highlighting for code blocks with Highlight.js
    • Dark/light theme toggle with localStorage persistence
    • Automatic language detection from file extensions
    • Smooth animations and transitions
    • Mobile-friendly layout with sticky navigation
    • Reads project metadata from arty.yml using yq

${GREEN}LANDING PAGE MODE:${NC}
    Generates a stylish landing page for butter.sh with carbon theme.

    ${CYAN}Features:${NC}
    • Cool, urban military carbon minimalistic theme
    • Hero section with gradient CTA buttons
    • Responsive header with navigation and mobile menu
    • Theme switcher (dark/light mode)
    • Project cards with hover effects and descriptions
    • GitHub integration with iconset.css icons
    • Customizable project list via JSON (string or file)
    • JSON validation with jq

${GREEN}EXAMPLES:${NC}
    ${CYAN}# Generate docs for current directory${NC}
    leaf.sh

    ${CYAN}# Generate docs for specific project with custom logo${NC}
    leaf.sh /path/to/project --logo ./icon.svg

    ${CYAN}# Generate docs with custom output directory${NC}
    leaf.sh /path/to/project -o ./public

    ${CYAN}# Generate butter.sh landing page${NC}
    leaf.sh --landing --github https://github.com/my-org

    ${CYAN}# Generate landing with custom projects (inline JSON)${NC}
    leaf.sh --landing --projects '[
      {"url":"https://proj.sh","label":"proj.sh","desc":"Description","class":"project-card"}
    ]'

    ${CYAN}# Generate landing with projects from file${NC}
    leaf.sh --landing --projects-file ./projects.json

    ${CYAN}# Generate with custom base path (for subdirectory deployment)${NC}
    leaf.sh --base-path /docs/

${GREEN}DEPENDENCIES:${NC}
    • ${YELLOW}yq${NC} - YAML parser (required)
      Install: https://github.com/mikefarah/yq#install
    • ${YELLOW}jq${NC} - JSON processor (required)
      Install: https://stedolan.github.io/jq/download/

${GREEN}PROJECT STRUCTURE:${NC}
    For best results, structure your arty.sh project like this:
    
    your-project/
    ├── arty.yml           ${BLUE}# Project metadata (name, version, description, etc.)${NC}
    ├── README.md          ${BLUE}# Main documentation${NC}
    ├── LICENSE            ${BLUE}# License file${NC}
    ├── main.sh            ${BLUE}# Source files${NC}
    ├── _assets/
    │   └── icon/
    │       └── icon.svg   ${BLUE}# Project icon${NC}
    └── examples/
        └── usage.sh       ${BLUE}# Example files${NC}

${GREEN}PROJECTS JSON FORMAT:${NC}
    For landing page mode, projects JSON should be an array:
    [
      {
        "url": "https://project.com",
        "label": "Project Name",
        "desc": "Project description",
        "class": "card-project"
      }
    ]

${GREEN}SUPPORTED FILE TYPES:${NC}
    Shell (.sh, .bash), JavaScript (.js), Python (.py), Ruby (.rb),
    Go (.go), Rust (.rs), Java (.java), C/C++ (.c, .h, .cpp, .hpp)

${GREEN}VERSION:${NC}
    leaf.sh v2.2.0

${GREEN}MORE INFORMATION:${NC}
    GitHub: https://github.com/butter-sh/leaf.sh
    Documentation: https://leaf.sh/docs

EOF
}

# Show version
show_version() {
	cat <<EOF
${CYAN}leaf.sh${NC} version ${GREEN}2.2.0${NC}
Part of the ${CYAN}butter.sh${NC} ecosystem

Generated by: ${YELLOW}hammer.sh${NC}
License: ${YELLOW}MIT${NC}

${BLUE}Features:${NC}
  • Documentation generation from arty.sh projects
  • Landing page generation for butter.sh
  • YAML parsing with yq
  • JSON processing with jq
  • Modern, responsive design
  • Dark/light theme support

${BLUE}Website:${NC} https://leaf.sh
${BLUE}GitHub:${NC} https://github.com/butter-sh/leaf.sh
EOF
}

# Parse command line arguments
parse_args() {
	local projects_json=""

	while [[ $# -gt 0 ]]; do
		case $1 in
		-h | --help)
			show_usage
			exit 0
			;;
		--version)
			show_version
			exit 0
			;;
		--debug)
			DEBUG=1
			shift
			;;
		--landing)
			MODE="landing"
			shift
			;;
		--logo)
			LOGO_PATH="$2"
			shift 2
			;;
		--base-path)
			BASE_PATH="$2"
			shift 2
			;;
		--github)
			GITHUB_URL="$2"
			shift 2
			;;
		--projects)
			projects_json="$2"
			shift 2
			;;
		--projects-file)
			PROJECTS_FILE="$2"
			shift 2
			;;
		-o | --output)
			OUTPUT_DIR="$2"
			shift 2
			;;
		-*)
			log_error "Unknown option: $1"
			echo
			show_usage
			exit 1
			;;
		*)
			PROJECT_DIR="$1"
			shift
			;;
		esac
	done

	# Export projects JSON if provided
	if [[ -n "$projects_json" ]]; then
		PROJECTS_JSON="$projects_json"
	fi
}

# Parse YAML using yq
parse_yaml() {
	local file="$1"
	local key="$2"

	if [[ ! -f "$file" ]]; then
		log_debug "YAML file not found: $file"
		echo ""
		return
	fi

	local value=$(yq eval ".${key}" "$file" 2>/dev/null | grep -v '^null$' || echo "")
	log_debug "Parsed ${key} from ${file}: ${value}"
	echo "$value"
}

# Parse and validate JSON using jq
parse_json() {
	local json_input="$1"
	local query="${2:-.}" # Default to identity filter

	log_debug "Parsing JSON with query: $query"

	# Try to parse and validate JSON
	local result
	if result=$(echo "$json_input" | jq -r "$query" 2>/dev/null); then
		log_debug "JSON parsed successfully"
		echo "$result"
		return 0
	else
		log_error "Invalid JSON format"
		return 1
	fi
}

# Validate JSON structure for projects
validate_projects_json() {
	local json="$1"

	log_debug "Validating projects JSON structure"

	# Check if it's an array
	if ! echo "$json" | jq -e 'type == "array"' >/dev/null 2>&1; then
		log_error "Projects JSON must be an array"
		return 1
	fi

	# Check if array is not empty
	local count=$(echo "$json" | jq 'length')
	if [[ "$count" -eq 0 ]]; then
		log_warn "Projects JSON array is empty"
	fi

	log_debug "Found $count project(s) in JSON"

	# Validate each project has required fields
	local i=0
	while [[ $i -lt $count ]]; do
		local project=$(echo "$json" | jq -r ".[$i]")
		local url=$(echo "$project" | jq -r '.url // empty')
		local label=$(echo "$project" | jq -r '.label // empty')

		if [[ -z "$url" || -z "$label" ]]; then
			log_warn "Project at index $i is missing required fields (url, label)"
		else
			log_debug "Project $i: $label -> $url"
		fi

		i=$((i + 1))
	done

	return 0
}

# Read JSON from file
read_json_file() {
	local file="$1"

	if [[ ! -f "$file" ]]; then
		log_error "JSON file not found: $file"
		return 1
	fi

	log_debug "Reading JSON from file: $file"

	local json
	if json=$(jq -c '.' "$file" 2>/dev/null); then
		log_success "JSON file loaded successfully"
		echo "$json"
		return 0
	else
		log_error "Failed to parse JSON file: $file"
		return 1
	fi
}

# Read file content safely
read_file() {
	local file="$1"
	if [[ -f "$file" ]]; then
		cat "$file"
	else
		log_debug "File not found: $file"
		echo ""
	fi
}

# Detect language from file extension
detect_language() {
	local file="$1"
	local ext="${file##*.}"

	case "$ext" in
	sh | bash) echo "bash" ;;
	js) echo "javascript" ;;
	ts) echo "typescript" ;;
	py) echo "python" ;;
	rb) echo "ruby" ;;
	go) echo "go" ;;
	rs) echo "rust" ;;
	java) echo "java" ;;
	c | h) echo "c" ;;
	cpp | cc | cxx | hpp) echo "cpp" ;;
	php) echo "php" ;;
	html | htm) echo "html" ;;
	css) echo "css" ;;
	json) echo "json" ;;
	yaml | yml) echo "yaml" ;;
	xml) echo "xml" ;;
	sql) echo "sql" ;;
	md | markdown) echo "markdown" ;;
	*) echo "plaintext" ;;
	esac
}

# Get icon path
get_icon() {
	# Check if custom logo provided
	if [[ -n "$LOGO_PATH" && -f "$LOGO_PATH" ]]; then
		log_debug "Using custom logo: $LOGO_PATH"
		echo "$LOGO_PATH"
		return
	fi

	local icon_dir="${PROJECT_DIR}/_assets/icon"
	local icon_path=""

	# Search for icon files in priority order
	local icon_files=("icon.svg" "icon-v2.svg" "icon-simple.svg" "icon.png")

	for icon_file in "${icon_files[@]}"; do
		if [[ -f "${icon_dir}/${icon_file}" ]]; then
			icon_path="${icon_dir}/${icon_file}"
			log_debug "Found icon: $icon_path"
			break
		fi
	done

	echo "$icon_path"
}

# Scan source files
scan_source_files() {
	local files=()

	log_debug "Scanning source files in: $PROJECT_DIR"

	while IFS= read -r -d $'\\0' file; do
		local rel_path="${file#${PROJECT_DIR}/}"
		# Skip common directories and minified files
		if [[ "$rel_path" =~ ^(docs|node_modules|\\.git|\\.)|\\.min\\. ]]; then
			continue
		fi
		files+=("$file")
		log_debug "Found source file: $rel_path"
	done < <(find "$PROJECT_DIR" -type f -o -name "*.sh" -o -name "*.bash" -o -name "*.js" -o -name "*.py" -o -name "*.rb" -o -name "*.go" -o -name "*.rs" -print0 2>/dev/null || true)

	printf '%s\
' "${files[@]}"
}

# Scan example files
scan_examples() {
	local examples_dir="${PROJECT_DIR}/examples"
	local examples=()

	if [[ ! -d "$examples_dir" ]]; then
		log_debug "Examples directory not found: $examples_dir"
		return
	fi

	log_debug "Scanning examples in: $examples_dir"

	while IFS= read -r -d $'\\0' file; do
		examples+=("$file")
		log_debug "Found example: ${file#${examples_dir}/}"
	done < <(find "$examples_dir" -type f -print0 2>/dev/null || true)

	printf '%s\
' "${examples[@]}"
}

# Generate documentation page
generate_docs_page() {
	log_info "Generating documentation..."

	local arty_yml="${PROJECT_DIR}/arty.yml"
	local readme_md="${PROJECT_DIR}/README.md"

	# Parse project metadata using yq
	local project_name=$(parse_yaml "$arty_yml" "name")
	local project_version=$(parse_yaml "$arty_yml" "version")
	local project_desc=$(parse_yaml "$arty_yml" "description")
	local project_author=$(parse_yaml "$arty_yml" "author")
	local project_license=$(parse_yaml "$arty_yml" "license")

	# Fallback to directory name if no name in arty.yml
	[[ -z "$project_name" ]] && project_name=$(basename "$PROJECT_DIR")

	log_debug "Project: $project_name v$project_version"
	log_debug "Description: $project_desc"

	# Read README
	local readme_content=$(read_file "$readme_md")
	if [[ -z "$readme_content" ]]; then
		log_warn "README.md not found, using placeholder"
		readme_content="No README.md file found in project."
	fi

	# Get icon
	local icon_path=$(get_icon)
	local icon_svg=""
	if [[ -n "$icon_path" ]]; then
		icon_svg=$(cat "$icon_path")
		log_success "Loaded icon from: ${icon_path#${PROJECT_DIR}/}"
	else
		log_warn "No icon found in _assets/icon/, using default"
	fi

	# Scan files
	local source_files=($(scan_source_files))
	local example_files=($(scan_examples))

	log_info "Found ${#source_files[@]} source files and ${#example_files[@]} examples"

	# Create output directory
	mkdir -p "$OUTPUT_DIR"

	# Generate HTML with all features
	generate_docs_html "$project_name" "$project_version" "$project_desc" "$project_author" "$project_license" "$icon_svg" "$readme_content" "${source_files[@]}" "---" "${example_files[@]}"

	log_success "Documentation generated at: ${OUTPUT_DIR}/index.html"
}

# Generate documentation HTML
generate_docs_html() {
	local proj_name="$1"
	local proj_version="$2"
	local proj_desc="$3"
	local proj_author="$4"
	local proj_license="$5"
	local icon="$6"
	local readme="$7"
	shift 7

	# Collect source files until separator
	local sources=()
	while [[ $# -gt 0 && "$1" != "---" ]]; do
		sources+=("$1")
		shift
	done
	shift # Skip separator

	# Remaining are examples
	local examples=("$@")

	cat >"${OUTPUT_DIR}/index.html" <<'EOFDOCS'
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>%%PROJECT_NAME%% - Documentation</title>
    <meta name="description" content="%%PROJECT_DESC%%">
    <base href="%%BASE_PATH%%">
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
        * { font-family: 'Inter', system-ui, sans-serif; }
        code, pre { font-family: 'JetBrains Mono', monospace !important; }
        .icon-float { animation: float 3s ease-in-out infinite; }
        @keyframes float { 0%, 100% { transform: translateY(0px); } 50% { transform: translateY(-10px); } }
        .gradient-text {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
    </style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 min-h-screen">
    <nav class="sticky top-0 z-50 bg-white/80 dark:bg-slate-900/80 backdrop-blur-lg border-b border-slate-200 dark:border-slate-700">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center space-x-3">
                    <div class="w-10 h-10">%%ICON%%</div>
                    <span class="text-xl font-bold text-slate-900 dark:text-white">%%PROJECT_NAME%%</span>
                    <span class="px-2 py-1 text-xs font-semibold text-purple-600 dark:text-purple-400 bg-purple-100 dark:bg-purple-900/30 rounded-full">%%VERSION%%</span>
                </div>
                <div class="flex items-center space-x-4">
                    <a href="#overview" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Overview</a>
                    <a href="#source" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Source</a>
                    <a href="#examples" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Examples</a>
                    <a href="%%GITHUB_URL%%" target="_blank" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                    </a>
                    <button id="themeToggle" class="p-2 rounded-lg bg-slate-100 dark:bg-slate-800">
                        <svg class="w-5 h-5 dark:hidden" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"/></svg>
                        <svg class="w-5 h-5 hidden dark:block" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/></svg>
                    </button>
                </div>
            </div>
        </div>
    </nav>

    <section class="py-20 px-4">
        <div class="max-w-7xl mx-auto text-center">
            <div class="inline-block mb-8 icon-float"><div class="w-24 h-24 mx-auto">%%ICON%%</div></div>
            <h1 class="text-6xl font-bold mb-6 gradient-text">%%PROJECT_NAME%%</h1>
            <p class="text-2xl text-slate-600 dark:text-slate-300 mb-8 max-w-3xl mx-auto">%%PROJECT_DESC%%</p>
        </div>
    </section>

    <section id="overview" class="py-16 px-4">
        <div class="max-w-5xl mx-auto">
            <div class="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 md:p-12">
                <h2 class="text-4xl font-bold mb-8 text-slate-900 dark:text-white">Overview</h2>
                <div class="prose dark:prose-invert max-w-none">%%README%%</div>
            </div>
        </div>
    </section>

    <section id="source" class="py-16 px-4 bg-slate-100/50 dark:bg-slate-900/50">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-12 text-center text-slate-900 dark:text-white">Source Files</h2>
            <div class="grid gap-6">%%SOURCE_FILES%%</div>
        </div>
    </section>

    <section id="examples" class="py-16 px-4">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-12 text-center text-slate-900 dark:text-white">Examples</h2>
            <div class="grid gap-6">%%EXAMPLES%%</div>
        </div>
    </section>

    <footer class="py-12 px-4 bg-slate-900 dark:bg-black text-slate-300">
        <div class="max-w-7xl mx-auto text-center">
            <p class="text-lg mb-2">Generated by <span class="font-semibold text-purple-400">leaf.sh</span></p>
            <p class="text-sm text-slate-500">Part of the <a href="%%GITHUB_URL%%" class="text-green-400 hover:text-green-300">butter.sh</a> ecosystem</p>
        </div>
    </footer>

    <script>
        hljs.highlightAll();
        const toggle = document.getElementById('themeToggle');
        const html = document.documentElement;
        const theme = localStorage.getItem('theme') || 'light';
        if (theme === 'dark') html.classList.add('dark');
        toggle.addEventListener('click', () => {
            html.classList.toggle('dark');
            localStorage.setItem('theme', html.classList.contains('dark') ? 'dark' : 'light');
        });
        if (typeof marked !== 'undefined') {
            marked.setOptions({
                highlight: (code, lang) => {
                    if (lang && hljs.getLanguage(lang)) {
                        return hljs.highlight(code, { language: lang }).value;
                    }
                    return hljs.highlightAuto(code).value;
                }
            });
        }
    </script>
</body>
</html>
EOFDOCS

	# Replace placeholders
	sed -i "s|%%PROJECT_NAME%%|${proj_name}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%VERSION%%|${proj_version:-1.0.0}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%PROJECT_DESC%%|${proj_desc:-Documentation}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%BASE_PATH%%|${BASE_PATH}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%GITHUB_URL%%|${GITHUB_URL}|g" "${OUTPUT_DIR}/index.html"

	# Handle icon
	if [[ -n "$icon" ]]; then
		local icon_escaped=$(echo "$icon" | sed 's/[&/\\]/\\\\&/g' | tr '\
' ' ')
		sed -i "s|%%ICON%%|${icon_escaped}|g" "${OUTPUT_DIR}/index.html"
	else
		sed -i "s|%%ICON%%|<svg class=\"w-full h-full\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"/></svg>|g" "${OUTPUT_DIR}/index.html"
	fi

	# Generate source files HTML
	local src_html=""
	for file in "${sources[@]}"; do
		[[ ! -f "$file" ]] && continue
		local name=$(basename "$file")
		local rel="${file#${PROJECT_DIR}/}"
		local lang=$(detect_language "$file")
		local code=$(cat "$file" | sed 's/&/\\&amp;/g; s/</\\&lt;/g; s/>/\\&gt;/g')
		src_html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden\">"
		src_html+="<div class=\"bg-gradient-to-r from-blue-500 to-blue-600 px-6 py-4\">"
		src_html+="<h3 class=\"text-xl font-semibold text-white\">${name}</h3>"
		src_html+="<p class=\"text-blue-100 text-sm\">${rel}</p></div>"
		src_html+="<div class=\"p-6\"><pre><code class=\"language-${lang}\">${code}</code></pre></div></div>"
	done
	[[ -z "$src_html" ]] && src_html="<p class=\"text-center text-slate-600\">No source files found.</p>"
	echo "$src_html" >/tmp/src.html
	sed -i "/%%SOURCE_FILES%%/r /tmp/src.html" "${OUTPUT_DIR}/index.html"
	sed -i "/%%SOURCE_FILES%%/d" "${OUTPUT_DIR}/index.html"

	# Generate examples HTML
	local ex_html=""
	for file in "${examples[@]}"; do
		[[ ! -f "$file" ]] && continue
		local name=$(basename "$file")
		local lang=$(detect_language "$file")
		local code=$(cat "$file" | sed 's/&/\\&amp;/g; s/</\\&lt;/g; s/>/\\&gt;/g')
		ex_html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden\">"
		ex_html+="<div class=\"bg-gradient-to-r from-green-500 to-green-600 px-6 py-4\">"
		ex_html+="<h3 class=\"text-xl font-semibold text-white\">${name}</h3></div>"
		ex_html+="<div class=\"p-6\"><pre><code class=\"language-${lang}\">${code}</code></pre></div></div>"
	done
	[[ -z "$ex_html" ]] && ex_html="<p class=\"text-center text-slate-600\">No examples found.</p>"
	echo "$ex_html" >/tmp/ex.html
	sed -i "/%%EXAMPLES%%/r /tmp/ex.html" "${OUTPUT_DIR}/index.html"
	sed -i "/%%EXAMPLES%%/d" "${OUTPUT_DIR}/index.html"

	# Handle README
	local readme_html=$(echo "$readme" | sed ':a;N;$!ba;s/\
/<br>/g')
	echo "$readme_html" >/tmp/readme.html
	sed -i "/%%README%%/r /tmp/readme.html" "${OUTPUT_DIR}/index.html"
	sed -i "/%%README%%/d" "${OUTPUT_DIR}/index.html"

	rm -f /tmp/src.html /tmp/ex.html /tmp/readme.html
}

# Generate butter.sh landing page
generate_landing_page() {
	log_info "Generating butter.sh landing page..."

	mkdir -p "$OUTPUT_DIR"

	# Default projects if none provided
	local projects_default='[
        {"url":"https://hammer.sh","label":"hammer.sh","desc":"Configurable bash project generator","class":"card-project"},
        {"url":"https://arty.sh","label":"arty.sh","desc":"Bash library repository manager","class":"card-project"},
        {"url":"https://leaf.sh","label":"leaf.sh","desc":"Beautiful documentation generator","class":"card-project"}
    ]'

	local projects=""

	# Priority: --projects-file > --projects > default
	if [[ -n "$PROJECTS_FILE" ]]; then
		log_info "Loading projects from file: $PROJECTS_FILE"
		if projects=$(read_json_file "$PROJECTS_FILE"); then
			if validate_projects_json "$projects"; then
				log_success "Projects JSON loaded and validated from file"
			else
				log_error "Invalid projects JSON in file"
				return 1
			fi
		else
			return 1
		fi
	elif [[ -n "$PROJECTS_JSON" ]]; then
		log_info "Using projects from command line"
		if parse_json "$PROJECTS_JSON" >/dev/null; then
			projects="$PROJECTS_JSON"
			if validate_projects_json "$projects"; then
				log_success "Projects JSON validated"
			else
				log_error "Invalid projects JSON"
				return 1
			fi
		else
			log_error "Failed to parse projects JSON"
			return 1
		fi
	else
		log_info "Using default butter.sh projects"
		projects="$projects_default"
	fi

	cat >"${OUTPUT_DIR}/index.html" <<'EOFLANDING'
<!DOCTYPE html>
<html lang="en" class="scroll-smooth dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>butter.sh - Modern Bash Development Ecosystem</title>
    <meta name="description" content="A collection of modern bash development tools">
    <base href="%%BASE_PATH%%">
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="../_assets/styles/iconset.css">
    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap');
        * { font-family: 'Inter', system-ui, sans-serif; }
        
        :root {
            --carbon-light: #86efac;
            --carbon-light-dim: #4ade80;
            --carbon-bg: #1a1a1a;
            --carbon-surface: #2c3e50;
        }
        
        /* Carbon texture background */
        .carbon-bg {
            background: linear-gradient(135deg, #2c3e50 0%, #1a1a1a 100%);
            position: relative;
        }
        .carbon-bg::before {
            content: '';
            position: absolute;
            inset: 0;
            background-image: 
                repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(134, 239, 172, 0.03) 2px, rgba(134, 239, 172, 0.03) 4px),
                repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(134, 239, 172, 0.03) 2px, rgba(134, 239, 172, 0.03) 4px);
            opacity: 0.5;
        }
        
        /* Gradient CTA */
        .cta-gradient {
            background: linear-gradient(135deg, var(--carbon-light) 0%, var(--carbon-light-dim) 100%);
            box-shadow: 0 0 20px rgba(134, 239, 172, 0.3);
            transition: all 0.3s ease;
        }
        .cta-gradient:hover {
            box-shadow: 0 0 30px rgba(134, 239, 172, 0.5);
            transform: translateY(-2px);
        }
        
        .cta-secondary {
            border: 2px solid var(--carbon-light);
            color: var(--carbon-light);
            transition: all 0.3s ease;
        }
        .cta-secondary:hover {
            background: rgba(134, 239, 172, 0.1);
            box-shadow: 0 0 20px rgba(134, 239, 172, 0.2);
        }
        
        /* Project cards */
        .card-project {
            background: rgba(44, 62, 80, 0.6);
            border: 1px solid rgba(134, 239, 172, 0.2);
            backdrop-filter: blur(10px);
            transition: all 0.3s ease;
        }
        .card-project:hover {
            border-color: var(--carbon-light);
            box-shadow: 0 10px 30px rgba(134, 239, 172, 0.2);
            transform: translateY(-4px);
        }
        
        /* Light mode overrides */
        html:not(.dark) {
            --carbon-bg: #f0f4f8;
            --carbon-surface: #ffffff;
        }
        html:not(.dark) .carbon-bg {
            background: linear-gradient(135deg, #f0f4f8 0%, #e2e8f0 100%);
        }
        html:not(.dark) .carbon-bg::before {
            background-image: 
                repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(74, 222, 128, 0.05) 2px, rgba(74, 222, 128, 0.05) 4px),
                repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(74, 222, 128, 0.05) 2px, rgba(74, 222, 128, 0.05) 4px);
        }
        html:not(.dark) .card-project {
            background: rgba(255, 255, 255, 0.8);
            border-color: rgba(74, 222, 128, 0.3);
        }
        
        /* Mobile menu */
        .mobile-menu {
            display: none;
            transition: all 0.3s ease;
        }
        .mobile-menu.active {
            display: block;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
            animation: fadeIn 0.6s ease-out forwards;
        }
    </style>
</head>
<body class="carbon-bg min-h-screen text-slate-100">
    <!-- Header -->
    <header class="sticky top-0 z-50 bg-slate-900/80 backdrop-blur-lg border-b border-slate-700">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center space-x-3">
                    <div class="w-10 h-10">%%LOGO%%</div>
                    <span class="text-2xl font-bold" style="color: var(--carbon-light);">butter.sh</span>
                </div>
                
                <nav class="hidden md:flex items-center space-x-6">
                    <a href="#projects" class="text-slate-300 hover:text-white transition">Projects</a>
                    <a href="%%GITHUB_URL%%" target="_blank" class="flex items-center space-x-2 text-slate-300 hover:text-white transition">
                        <i class="icon icon-github"></i>
                        <span>GitHub</span>
                    </a>
                    <button id="themeToggle" class="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 transition">
                        <i class="icon icon-moon dark:hidden"></i>
                        <i class="icon icon-sun hidden dark:inline-block"></i>
                    </button>
                </nav>
                
                <button id="mobileMenuBtn" class="md:hidden p-2">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                    </svg>
                </button>
            </div>
            
            <div id="mobileMenu" class="mobile-menu md:hidden py-4 space-y-2">
                <a href="#projects" class="block px-4 py-2 text-slate-300 hover:bg-slate-800 rounded">Projects</a>
                <a href="%%GITHUB_URL%%" target="_blank" class="block px-4 py-2 text-slate-300 hover:bg-slate-800 rounded">GitHub</a>
            </div>
        </div>
    </header>

    <!-- Hero Section -->
    <section class="relative py-32 px-4 overflow-hidden">
        <div class="max-w-7xl mx-auto text-center relative z-10">
            <div class="mb-8">
                <div class="w-32 h-32 mx-auto">%%LOGO%%</div>
            </div>
            <h1 class="text-7xl font-black mb-6 animate-fade-in" style="color: var(--carbon-light);">
                butter.sh
            </h1>
            <p class="text-2xl text-slate-300 mb-12 max-w-3xl mx-auto animate-fade-in">
                Modern bash development tools for the command line renaissance
            </p>
            
            <div class="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in">
                <a href="%%GITHUB_URL%%" class="cta-gradient px-8 py-4 rounded-lg font-bold text-slate-900 text-lg">
                    Explore Projects
                </a>
                <a href="#projects" class="cta-secondary px-8 py-4 rounded-lg font-bold text-lg">
                    Learn More
                </a>
            </div>
        </div>
    </section>

    <!-- Projects Section -->
    <section id="projects" class="py-20 px-4">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-5xl font-bold mb-16 text-center" style="color: var(--carbon-light);">
                Our Projects
            </h2>
            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8" id="projectsGrid">
                <!-- Projects will be injected here -->
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="py-12 px-4 bg-slate-900 border-t border-slate-700">
        <div class="max-w-7xl mx-auto text-center">
            <div class="mb-4">
                <span class="text-3xl font-bold" style="color: var(--carbon-light);">butter.sh</span>
            </div>
            <p class="text-slate-400 mb-4">Building the future of bash development</p>
            <div class="flex justify-center space-x-6">
                <a href="%%GITHUB_URL%%" target="_blank" class="text-slate-400 hover:text-white transition">
                    <i class="icon icon-github icon-2xl"></i>
                </a>
            </div>
        </div>
    </footer>

    <script>
        // Theme toggle
        const toggle = document.getElementById('themeToggle');
        const html = document.documentElement;
        const theme = localStorage.getItem('theme') || 'dark';
        if (theme === 'light') html.classList.remove('dark');
        
        toggle.addEventListener('click', () => {
            html.classList.toggle('dark');
            localStorage.setItem('theme', html.classList.contains('dark') ? 'dark' : 'light');
        });
        
        // Mobile menu
        const mobileMenuBtn = document.getElementById('mobileMenuBtn');
        const mobileMenu = document.getElementById('mobileMenu');
        mobileMenuBtn.addEventListener('click', () => {
            mobileMenu.classList.toggle('active');
        });
        
        // Inject projects
        const projects = %%PROJECTS_JSON%%;
        const grid = document.getElementById('projectsGrid');
        projects.forEach((proj, i) => {
            const card = document.createElement('div');
            card.className = `${proj.class} p-8 rounded-xl animate-fade-in`;
            card.style.animationDelay = `${i * 0.1}s`;
            card.innerHTML = `
                <div class="flex items-center justify-between mb-4">
                    <h3 class="text-2xl font-bold" style="color: var(--carbon-light);">${proj.label}</h3>
                    <i class="icon icon-cube icon-xl" style="color: var(--carbon-light);"></i>
                </div>
                <p class="text-slate-300 mb-6">${proj.desc}</p>
                <a href="${proj.url}" target="_blank" class="inline-flex items-center space-x-2 text-white hover:underline">
                    <span>View Project</span>
                    <i class="icon icon-link"></i>
                </a>
            `;
            grid.appendChild(card);
        });
    </script>
</body>
</html>
EOFLANDING

	# Get logo
	local logo_svg=""
	if [[ -n "$LOGO_PATH" && -f "$LOGO_PATH" ]]; then
		logo_svg=$(cat "$LOGO_PATH")
		log_success "Using custom logo: $LOGO_PATH"
	else
		# Use butter.sh default logo if available
		local butter_logo="${PROJECT_DIR}/../butter.sh/_assets/brand/cube-carbon-light.svg"
		if [[ -f "$butter_logo" ]]; then
			logo_svg=$(cat "$butter_logo")
			log_success "Using butter.sh brand logo"
		else
			log_warn "Using default fallback logo"
			logo_svg='<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>'
		fi
	fi

	# Escape logo
	local logo_escaped=$(echo "$logo_svg" | sed 's/[&/\\]/\\\\&/g' | tr '\
' ' ')

	# Replace placeholders
	sed -i "s|%%LOGO%%|${logo_escaped}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%BASE_PATH%%|${BASE_PATH}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%GITHUB_URL%%|${GITHUB_URL}|g" "${OUTPUT_DIR}/index.html"
	sed -i "s|%%PROJECTS_JSON%%|${projects}|g" "${OUTPUT_DIR}/index.html"

	log_success "Landing page generated at: ${OUTPUT_DIR}/index.html"
}

# Main function
main() {
	# Check dependencies first
	if ! check_dependencies; then
		exit 1
	fi

	parse_args "$@"

	echo -e "${CYAN}"
	echo "╔═══════════════════════════════════════════╗"
	echo "║                                           ║"
	echo "║      🌿 leaf.sh Generator v2.2 🌿        ║"
	echo "║                                           ║"
	echo "║    Beautiful docs & landing pages        ║"
	echo "║       Powered by yq & jq parsers         ║"
	echo "║                                           ║"
	echo "╚═══════════════════════════════════════════╝"
	echo -e "${NC}"
	echo

	if [[ "$MODE" == "landing" ]]; then
		generate_landing_page
	else
		# Documentation mode
		if [[ ! -d "$PROJECT_DIR" ]]; then
			log_error "Project directory not found: $PROJECT_DIR"
			exit 1
		fi

		log_info "Scanning project: $PROJECT_DIR"
		generate_docs_page
	fi

	echo
	echo -e "${GREEN}═══════════════════════════════════════════${NC}"
	echo -e "${GREEN}Generation complete! 🎉${NC}"
	echo -e "${GREEN}═══════════════════════════════════════════${NC}"
	echo
	echo -e "📂 Output: ${CYAN}${OUTPUT_DIR}/index.html${NC}"
	echo -e "🌐 Open: ${BLUE}file://${OUTPUT_DIR}/index.html${NC}"
	echo
}

# Run main function
main "$@"
