#!/usr/bin/env bash

# leaf.sh - Beautiful documentation generator for arty.sh projects
# Version: 1.0.0
# Generated by hammer.sh

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
PROJECT_DIR="${1:-.}"
OUTPUT_DIR="${PROJECT_DIR}/docs"
ARTY_YML="${PROJECT_DIR}/arty.yml"
README_MD="${PROJECT_DIR}/README.md"
LICENSE="${PROJECT_DIR}/LICENSE"
ASSETS_DIR="${PROJECT_DIR}/_assets"
ICON_DIR="${ASSETS_DIR}/icon"
EXAMPLES_DIR="${PROJECT_DIR}/examples"

# Helper functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Parse YAML (simple parser for arty.yml)
parse_yaml() {
    local file="$1"
    local key="$2"
    
    if [[ ! -f "$file" ]]; then
        echo ""
        return
    fi
    
    # Simple YAML parsing for key: value pairs
    local value=$(grep "^${key}:" "$file" | head -1 | sed "s/^${key}://; s/^[[:space:]]*//; s/[[:space:]]*$//; s/^[\"']//; s/[\"']$//" || echo "")
    echo "$value"
}

# Convert markdown to HTML (basic conversion)
markdown_to_html() {
    local content="$1"
    
    # Escape HTML
    content=$(echo "$content" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
    
    # Convert headers
    content=$(echo "$content" | sed -E 's/^######[[:space:]]*(.*)/\<h6 class="text-lg font-semibold mt-4 mb-2 text-gray-800 dark:text-gray-200">\1<\/h6>/g')
    content=$(echo "$content" | sed -E 's/^#####[[:space:]]*(.*)/\<h5 class="text-xl font-semibold mt-4 mb-2 text-gray-800 dark:text-gray-200">\1<\/h5>/g')
    content=$(echo "$content" | sed -E 's/^####[[:space:]]*(.*)/\<h4 class="text-2xl font-semibold mt-6 mb-3 text-gray-800 dark:text-gray-200">\1<\/h4>/g')
    content=$(echo "$content" | sed -E 's/^###[[:space:]]*(.*)/\<h3 class="text-3xl font-semibold mt-8 mb-4 text-gray-900 dark:text-gray-100">\1<\/h3>/g')
    content=$(echo "$content" | sed -E 's/^##[[:space:]]*(.*)/\<h2 class="text-4xl font-bold mt-10 mb-4 text-gray-900 dark:text-gray-100">\1<\/h2>/g')
    content=$(echo "$content" | sed -E 's/^#[[:space:]]*(.*)/\<h1 class="text-5xl font-bold mt-12 mb-6 text-gray-900 dark:text-gray-100">\1<\/h1>/g')
    
    # Convert bold and italic
    content=$(echo "$content" | sed -E 's/\*\*([^*]+)\*\*/<strong class="font-semibold text-gray-900 dark:text-gray-100">\1<\/strong>/g')
    content=$(echo "$content" | sed -E 's/\*([^*]+)\*/<em class="italic text-gray-700 dark:text-gray-300">\1<\/em>/g')
    
    # Convert inline code
    content=$(echo "$content" | sed -E 's/`([^`]+)`/<code class="px-2 py-1 bg-gray-100 dark:bg-gray-800 text-pink-600 dark:text-pink-400 rounded text-sm font-mono">\1<\/code>/g')
    
    # Convert links
    content=$(echo "$content" | sed -E 's/\[([^]]+)\]\(([^)]+)\)/<a href="\2" class="text-blue-600 dark:text-blue-400 hover:underline">\1<\/a>/g')
    
    echo "$content"
}

# Get icon path
get_icon() {
    local icon_path=""
    
    if [[ -f "${ICON_DIR}/icon.svg" ]]; then
        icon_path="${ICON_DIR}/icon.svg"
    elif [[ -f "${ICON_DIR}/icon-v2.svg" ]]; then
        icon_path="${ICON_DIR}/icon-v2.svg"
    elif [[ -f "${ICON_DIR}/icon-simple.svg" ]]; then
        icon_path="${ICON_DIR}/icon-simple.svg"
    elif [[ -f "${ICON_DIR}/icon-alt.svg" ]]; then
        icon_path="${ICON_DIR}/icon-alt.svg"
    fi
    
    echo "$icon_path"
}

# Read file content safely
read_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cat "$file"
    else
        echo ""
    fi
}

# Detect language from file extension
detect_language() {
    local file="$1"
    local ext="${file##*.}"
    
    case "$ext" in
        sh|bash) echo "bash" ;;
        js) echo "javascript" ;;
        py) echo "python" ;;
        rb) echo "ruby" ;;
        go) echo "go" ;;
        rs) echo "rust" ;;
        java) echo "java" ;;
        c|h) echo "c" ;;
        cpp|cc|cxx|hpp) echo "cpp" ;;
        cs) echo "csharp" ;;
        php) echo "php" ;;
        html) echo "html" ;;
        css) echo "css" ;;
        json) echo "json" ;;
        xml) echo "xml" ;;
        yaml|yml) echo "yaml" ;;
        md) echo "markdown" ;;
        *) echo "plaintext" ;;
    esac
}

# Scan source files
scan_source_files() {
    local files=()
    
    # Find all script files (excluding hidden directories and docs)
    while IFS= read -r -d $'\0' file; do
        local rel_path="${file#${PROJECT_DIR}/}"
        
        # Skip docs, node_modules, .git, etc.
        if [[ "$rel_path" =~ ^(docs|node_modules|\.git|\.)|\.min\. ]]; then
            continue
        fi
        
        files+=("$file")
    done < <(find "$PROJECT_DIR" -type f \( -name "*.sh" -o -name "*.bash" -o -name "*.js" -o -name "*.py" \) -print0 2>/dev/null || true)
    
    printf '%s\n' "${files[@]}"
}

# Scan example files
scan_examples() {
    local examples=()
    
    if [[ -d "$EXAMPLES_DIR" ]]; then
        while IFS= read -r -d $'\0' file; do
            examples+=("$file")
        done < <(find "$EXAMPLES_DIR" -type f -print0 2>/dev/null || true)
    fi
    
    printf '%s\n' "${examples[@]}"
}

# Generate HTML page
generate_page() {
    log_info "Generating documentation..."
    
    # Parse project metadata
    local project_name=$(parse_yaml "$ARTY_YML" "name")
    local project_version=$(parse_yaml "$ARTY_YML" "version")
    local project_desc=$(parse_yaml "$ARTY_YML" "description")
    local project_author=$(parse_yaml "$ARTY_YML" "author")
    local project_license=$(parse_yaml "$ARTY_YML" "license")
    
    # Use directory name if no project name found
    if [[ -z "$project_name" ]]; then
        project_name=$(basename "$PROJECT_DIR")
    fi
    
    # Read README content
    local readme_content=$(read_file "$README_MD")
    
    # Get icon
    local icon_path=$(get_icon)
    local icon_svg=""
    if [[ -n "$icon_path" ]]; then
        icon_svg=$(cat "$icon_path")
    fi
    
    # Scan files
    local source_files=($(scan_source_files))
    local example_files=($(scan_examples))
    
    # Create output directory
    mkdir -p "$OUTPUT_DIR"
    
    # Generate index.html
    cat > "${OUTPUT_DIR}/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT_NAME - Documentation</title>
    <meta name="description" content="PROJECT_DESCRIPTION">
    
    <!-- Tailwind CSS v4 -->
    <script src="https://cdn.tailwindcss.com/4.0.0-alpha.1"></script>
    
    <!-- Highlight.js for syntax highlighting -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js"></script>
    
    <!-- Marked.js for markdown parsing -->
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
        
        * {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
        }
        
        code, pre {
            font-family: 'JetBrains Mono', monospace !important;
        }
        
        .prose {
            max-width: none;
        }
        
        .prose pre {
            background: #282c34;
            border-radius: 0.5rem;
            padding: 1.5rem;
            overflow-x: auto;
        }
        
        .prose code {
            font-size: 0.875em;
        }
        
        /* Smooth scrolling */
        html {
            scroll-behavior: smooth;
        }
        
        /* Dark mode */
        .dark {
            color-scheme: dark;
        }
        
        /* Icon animation */
        .icon-float {
            animation: float 3s ease-in-out infinite;
        }
        
        @keyframes float {
            0%, 100% { transform: translateY(0px); }
            50% { transform: translateY(-10px); }
        }
        
        /* Gradient text */
        .gradient-text {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        /* Card hover effect */
        .card-hover {
            transition: all 0.3s ease;
        }
        
        .card-hover:hover {
            transform: translateY(-4px);
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
        }
    </style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 min-h-screen">
    <!-- Navigation -->
    <nav class="sticky top-0 z-50 bg-white/80 dark:bg-slate-900/80 backdrop-blur-lg border-b border-slate-200 dark:border-slate-700">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center space-x-3">
                    <div class="w-10 h-10 flex items-center justify-center">
                        PROJECT_ICON_SVG
                    </div>
                    <span class="text-xl font-bold text-slate-900 dark:text-white">PROJECT_NAME</span>
                    <span class="px-2 py-1 text-xs font-semibold text-purple-600 dark:text-purple-400 bg-purple-100 dark:bg-purple-900/30 rounded-full">PROJECT_VERSION</span>
                </div>
                
                <div class="flex items-center space-x-4">
                    <a href="#overview" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Overview</a>
                    <a href="#source" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Source</a>
                    <a href="#examples" class="text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition">Examples</a>
                    <button id="themeToggle" class="p-2 rounded-lg bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 transition">
                        <svg class="w-5 h-5 dark:hidden" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"/>
                        </svg>
                        <svg class="w-5 h-5 hidden dark:block" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section class="py-20 px-4">
        <div class="max-w-7xl mx-auto text-center">
            <div class="inline-block mb-8 icon-float">
                <div class="w-24 h-24 mx-auto">
                    PROJECT_ICON_SVG
                </div>
            </div>
            <h1 class="text-6xl font-bold mb-6 gradient-text">PROJECT_NAME</h1>
            <p class="text-2xl text-slate-600 dark:text-slate-300 mb-8 max-w-3xl mx-auto">PROJECT_DESCRIPTION</p>
            
            <div class="flex items-center justify-center space-x-6 text-slate-600 dark:text-slate-400">
                PROJECT_AUTHOR_DISPLAY
                PROJECT_LICENSE_DISPLAY
            </div>
        </div>
    </section>

    <!-- Overview Section -->
    <section id="overview" class="py-16 px-4">
        <div class="max-w-5xl mx-auto">
            <div class="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 md:p-12">
                <h2 class="text-4xl font-bold mb-8 text-slate-900 dark:text-white flex items-center">
                    <svg class="w-10 h-10 mr-3 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                    </svg>
                    Overview
                </h2>
                <div id="readme-content" class="prose prose-lg dark:prose-invert max-w-none">
                    README_CONTENT_HTML
                </div>
            </div>
        </div>
    </section>

    <!-- Source Files Section -->
    <section id="source" class="py-16 px-4 bg-slate-100/50 dark:bg-slate-900/50">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-12 text-slate-900 dark:text-white text-center flex items-center justify-center">
                <svg class="w-10 h-10 mr-3 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/>
                </svg>
                Source Files
            </h2>
            <div id="source-files" class="grid gap-6">
                SOURCE_FILES_HTML
            </div>
        </div>
    </section>

    <!-- Examples Section -->
    <section id="examples" class="py-16 px-4">
        <div class="max-w-7xl mx-auto">
            <h2 class="text-4xl font-bold mb-12 text-slate-900 dark:text-white text-center flex items-center justify-center">
                <svg class="w-10 h-10 mr-3 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"/>
                </svg>
                Examples
            </h2>
            <div id="example-files" class="grid gap-6">
                EXAMPLE_FILES_HTML
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="py-12 px-4 bg-slate-900 dark:bg-black text-slate-300">
        <div class="max-w-7xl mx-auto text-center">
            <p class="text-lg mb-2">Generated by <span class="font-semibold text-purple-400">leaf.sh</span></p>
            <p class="text-sm text-slate-500">Beautiful documentation for arty.sh projects</p>
        </div>
    </footer>

    <script>
        // Initialize Highlight.js
        hljs.highlightAll();
        
        // Theme toggle
        const themeToggle = document.getElementById('themeToggle');
        const html = document.documentElement;
        
        // Check for saved theme preference or default to 'light'
        const currentTheme = localStorage.getItem('theme') || 'light';
        if (currentTheme === 'dark') {
            html.classList.add('dark');
        }
        
        themeToggle.addEventListener('click', () => {
            html.classList.toggle('dark');
            const theme = html.classList.contains('dark') ? 'dark' : 'light';
            localStorage.setItem('theme', theme);
        });
        
        // Smooth scroll for navigation links
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            });
        });
        
        // Parse markdown in readme content if marked.js is available
        if (typeof marked !== 'undefined') {
            const readmeEl = document.getElementById('readme-content');
            if (readmeEl && readmeEl.textContent.trim()) {
                marked.setOptions({
                    highlight: function(code, lang) {
                        if (lang && hljs.getLanguage(lang)) {
                            return hljs.highlight(code, { language: lang }).value;
                        }
                        return hljs.highlightAuto(code).value;
                    }
                });
            }
        }
    </script>
</body>
</html>
HTMLEOF
    
    # Replace placeholders
    sed -i "s/PROJECT_NAME/${project_name}/g" "${OUTPUT_DIR}/index.html"
    sed -i "s/PROJECT_VERSION/${project_version:-1.0.0}/g" "${OUTPUT_DIR}/index.html"
    sed -i "s/PROJECT_DESCRIPTION/${project_desc:-Documentation}/g" "${OUTPUT_DIR}/index.html"
    
    # Handle icon SVG
    if [[ -n "$icon_svg" ]]; then
        # Escape special characters for sed
        icon_svg_escaped=$(echo "$icon_svg" | sed 's/[&/\]/\\&/g' | tr '\n' ' ')
        sed -i "s|PROJECT_ICON_SVG|${icon_svg_escaped}|g" "${OUTPUT_DIR}/index.html"
    else
        sed -i "s|PROJECT_ICON_SVG|<svg class=\"w-full h-full\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"/></svg>|g" "${OUTPUT_DIR}/index.html"
    fi
    
    # Handle author display
    if [[ -n "$project_author" ]]; then
        sed -i "s|PROJECT_AUTHOR_DISPLAY|<span>👤 ${project_author}</span>|g" "${OUTPUT_DIR}/index.html"
    else
        sed -i "s|PROJECT_AUTHOR_DISPLAY||g" "${OUTPUT_DIR}/index.html"
    fi
    
    # Handle license display
    if [[ -n "$project_license" ]]; then
        sed -i "s|PROJECT_LICENSE_DISPLAY|<span>📜 ${project_license}</span>|g" "${OUTPUT_DIR}/index.html"
    else
        sed -i "s|PROJECT_LICENSE_DISPLAY||g" "${OUTPUT_DIR}/index.html"
    fi
    
    # Process README content
    if [[ -n "$readme_content" ]]; then
        readme_html=$(markdown_to_html "$readme_content")
        # Use a temporary file for complex replacements
        echo "$readme_html" > /tmp/readme_tmp.html
        sed -i "/README_CONTENT_HTML/r /tmp/readme_tmp.html" "${OUTPUT_DIR}/index.html"
        sed -i "/README_CONTENT_HTML/d" "${OUTPUT_DIR}/index.html"
        rm -f /tmp/readme_tmp.html
    else
        sed -i "s|README_CONTENT_HTML|<p class=\"text-slate-600 dark:text-slate-400\">No README.md found.</p>|g" "${OUTPUT_DIR}/index.html"
    fi
    
    # Generate source files HTML
    local source_html=""
    if [[ ${#source_files[@]} -gt 0 ]]; then
        for file in "${source_files[@]}"; do
            local rel_path="${file#${PROJECT_DIR}/}"
            local filename=$(basename "$file")
            local lang=$(detect_language "$file")
            local content=$(cat "$file" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
            
            source_html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden card-hover\">"
            source_html+="<div class=\"bg-gradient-to-r from-blue-500 to-blue-600 px-6 py-4\">"
            source_html+="<h3 class=\"text-xl font-semibold text-white flex items-center\">"
            source_html+="<svg class=\"w-5 h-5 mr-2\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M9 2a2 2 0 00-2 2v8a2 2 0 002 2h6a2 2 0 002-2V6.414A2 2 0 0016.414 5L14 2.586A2 2 0 0012.586 2H9z\"/><path d=\"M3 8a2 2 0 012-2v10h8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z\"/></svg>"
            source_html+="${filename}</h3>"
            source_html+="<p class=\"text-blue-100 text-sm mt-1\">${rel_path}</p>"
            source_html+="</div>"
            source_html+="<div class=\"p-6\">"
            source_html+="<pre><code class=\"language-${lang}\">${content}</code></pre>"
            source_html+="</div></div>"
        done
    else
        source_html="<p class=\"text-center text-slate-600 dark:text-slate-400\">No source files found.</p>"
    fi
    
    echo "$source_html" > /tmp/source_tmp.html
    sed -i "/SOURCE_FILES_HTML/r /tmp/source_tmp.html" "${OUTPUT_DIR}/index.html"
    sed -i "/SOURCE_FILES_HTML/d" "${OUTPUT_DIR}/index.html"
    rm -f /tmp/source_tmp.html
    
    # Generate examples HTML
    local examples_html=""
    if [[ ${#example_files[@]} -gt 0 ]]; then
        for file in "${example_files[@]}"; do
            local rel_path="${file#${PROJECT_DIR}/}"
            local filename=$(basename "$file")
            local lang=$(detect_language "$file")
            local content=$(cat "$file" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g')
            
            examples_html+="<div class=\"bg-white dark:bg-slate-800 rounded-xl shadow-lg overflow-hidden card-hover\">"
            examples_html+="<div class=\"bg-gradient-to-r from-green-500 to-green-600 px-6 py-4\">"
            examples_html+="<h3 class=\"text-xl font-semibold text-white flex items-center\">"
            examples_html+="<svg class=\"w-5 h-5 mr-2\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path fill-rule=\"evenodd\" d=\"M3 5a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2h-2.22l.123.489.804.804A1 1 0 0113 18H7a1 1 0 01-.707-1.707l.804-.804L7.22 15H5a2 2 0 01-2-2V5zm5.771 7H5V5h10v7H8.771z\" clip-rule=\"evenodd\"/></svg>"
            examples_html+="${filename}</h3>"
            examples_html+="<p class=\"text-green-100 text-sm mt-1\">${rel_path}</p>"
            examples_html+="</div>"
            examples_html+="<div class=\"p-6\">"
            examples_html+="<pre><code class=\"language-${lang}\">${content}</code></pre>"
            examples_html+="</div></div>"
        done
    else
        examples_html="<p class=\"text-center text-slate-600 dark:text-slate-400\">No example files found.</p>"
    fi
    
    echo "$examples_html" > /tmp/examples_tmp.html
    sed -i "/EXAMPLE_FILES_HTML/r /tmp/examples_tmp.html" "${OUTPUT_DIR}/index.html"
    sed -i "/EXAMPLE_FILES_HTML/d" "${OUTPUT_DIR}/index.html"
    rm -f /tmp/examples_tmp.html
    
    log_success "Documentation generated at: ${OUTPUT_DIR}/index.html"
}

# Show usage
show_usage() {
    cat << EOF
leaf.sh - Beautiful documentation generator for arty.sh projects

USAGE:
    leaf.sh [project-dir]

ARGUMENTS:
    project-dir    Path to arty.sh project (default: current directory)

DESCRIPTION:
    Generates a beautiful static HTML documentation website from your arty.sh
    project, including README, source files, examples, and project metadata.

FEATURES:
    • Modern, responsive design with Tailwind CSS v4
    • Syntax highlighting for code blocks
    • Dark/light theme toggle
    • Automatic language detection
    • Smooth animations and transitions
    • Mobile-friendly layout

EXAMPLES:
    # Generate docs for current directory
    leaf.sh

    # Generate docs for specific project
    leaf.sh /path/to/my-project

OUTPUT:
    Documentation will be generated in: [project-dir]/docs/index.html

EOF
}

# Main function
main() {
    # Check for help flag
    if [[ "${1:-}" == "-h" ]] || [[ "${1:-}" == "--help" ]]; then
        show_usage
        exit 0
    fi
    
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════╗"
    echo "║                                           ║"
    echo "║      🌿 leaf.sh Generator 🌿      ║"
    echo "║                                           ║"
    echo "║    Beautiful docs for arty.sh projects   ║"
    echo "║                                           ║"
    echo "╚═══════════════════════════════════════════╝"
    echo -e "${NC}"
    echo
    
    # Check if project directory exists
    if [[ ! -d "$PROJECT_DIR" ]]; then
        log_error "Project directory not found: $PROJECT_DIR"
        exit 1
    fi
    
    log_info "Scanning project: $PROJECT_DIR"
    
    # Check for arty.yml
    if [[ ! -f "$ARTY_YML" ]]; then
        log_warn "No arty.yml found. Generating basic documentation..."
    fi
    
    # Generate documentation
    generate_page
    
    echo
    echo -e "${GREEN}═══════════════════════════════════════════${NC}"
    echo -e "${GREEN}Documentation generated successfully! 🎉${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════${NC}"
    echo
    echo -e "📂 Output: ${CYAN}${OUTPUT_DIR}/index.html${NC}"
    echo -e "🌐 Open in browser:"
    echo -e "   ${BLUE}file://${OUTPUT_DIR}/index.html${NC}"
    echo
}

# Run main function
main "$@"
